- name: Accept virtualbox-ext-pack license (accept UI button)
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: 'true'
    vtype: select

- name: Install dependent packages and VirtualBox Hypervisor
  apt:
    pkg:
      - apt-transport-https
      - virtualbox
      - virtualbox-ext-pack
    update_cache: yes

- name: Download the latest version of Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: '/usr/local/bin/minikube'
    mode: '755'

 

