---
- name: Include version-specific variables for {{ ansible_distribution }}
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Install Java on {{ ansible_distribution }} OS distribution
  include_tasks: java-{{ ansible_distribution }}.yml
  # vars:
  #   java_package: {{java_package}}

