- name: Install dependent packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
    update_cache: yes

- name: Add Google Cloud public signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: present
 
- name: Add Kubernetes apt repository entry
  apt_repository:
    filename: kubernetes
    repo: >-
      deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] 
      https://apt.kubernetes.io/ kubernetes-xenial main 
    state: present

- name: Install Kubectl
  apt:
    name: kubectl
    update_cache: yes
    state: present
