- name: Install dependent packages
  apt:
    pkg:
      - ca-certificates
      - gnupg
    update_cache: yes

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Retrieve architecture of packages dpkg installs
  command: dpkg --print-architecture
  register: dpkg_arch

# - debug:
#     msg: "Debian package architecture is {{ dpkg_arch.stdout }}" 
  
- name: Add Docker apt repository entry
  apt_repository:
    filename: docker
    repo: >-
      deb [arch={{ dpkg_arch.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] 
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable 
    state: present

- name: Install Docker Engine and containerd
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io 
    update_cache: yes

- name: Add user {{ ansible_user }} to group docker
  user:    
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

